<?php
/**
 * Created by PhpStorm.
 * User: jochemgruter
 * Date: 07-02-19
 * Time: 15:57
 */

namespace Gruter\ResourceViewer\Actions;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;

class Delete extends Action
{

    public $icon = 'fa-trash';

    public $displayOnRow = true;

    public function handle(Request $request, Collection $models)
    {
        foreach($models as $model){
            $model->delete();
        }
    }

    public function fields($model)
    {
        // TODO: Implement fields() method.
    }

    public function canRun(Collection $models)
    {
        return parent::canRun($models); // TODO: Change the autogenerated stub
    }


}
